### PR TITLE
Mango python

### PR DESCRIPTION
**Pull request by jpdna**
Given this PR, in python you can do:
```
from bdgenomics.adam.adamContext import ADAMContext
from bdgenomics.adam.rdd import AlignmentRecordRDD
ac = ADAMContext(sc)
alignmentFile = "small.sam"
reads = ac.loadAlignments(alignmentFile)
json = ac._jvm.org.bdgenomics.mango.converters.GA4GHutil.alignmentRecordRDDtoJSON(reads._jvmRdd)
```
and get back JSON
```
u'{\n  "alignments": [{\n    "id": "",\n    "readGroupId": "1",\n    "fragmentName": "simread:1:26472783:false",\n    "improperPlacement": true,\n    "duplicateFragment": false,\n    "numberReads": 1,\n    "fragmentLength": 0,\n    "readNumber": 0,\n    "failedVendorQualityChecks": false,\n    "alignment": {\n      "position": {\n        "referenceName": "1",\n        "position": "26472783",\n        "strand": "NEG_STRAND"\n      },\n      "mappingQuality": 60,\n      "cigar": [{\n        "operation": "ALIGNMENT_MATCH",\n        "operationLength": "75",\n        "referenceSequence": ""\n      }]\n    },\n    "secondaryAlignment": false,\n    "supplementaryAlignment": false,\n    "alignedSequence": "GTATAAGAGCAGCCTTATTCCTATTTATAATCAGGGTGAAACACCTGTGCCAATGCCAAGACAGGGGTGCCAAGA",\n    "alignedQuality": []\n  }
...
```

### CODE REVIEW

**Comment by akmorrow13** [comment]
@jpdna can you send me the entire json output so I can test it?

**Comment by akmorrow13** [comment]
@jpdna the json was just missing ']}' after adding that, we get a read!

screen shot 2017-09-11 at 12 45 37 pm

**Comment by akmorrow13** [comment]
We should merge these in as a separate PR to bigddatagenomics/mango. Nothing here is dependent on python

**Comment by jpdna** [comment]
Here is the full JSON
```
{
  "alignments": [{
    "id": "",
    "readGroupId": "1",
    "fragmentName": "simread:1:26472783:false",
    "improperPlacement": true,
    "duplicateFragment": false,
    "numberReads": 1,
    "fragmentLength": 0,
    "readNumber": 0,
    "failedVendorQualityChecks": false,
    "alignment": {
      "position": {
        "referenceName": "1",
        "position": "26472783",
        "strand": "NEG_STRAND"
      },
      "mappingQuality": 60,
      "cigar": [{
        "operation": "ALIGNMENT_MATCH",
        "operationLength": "75",
        "referenceSequence": ""
      }]
    },
    "secondaryAlignment": false,
    "supplementaryAlignment": false,
    "alignedSequence": "GTATAAGAGCAGCCTTATTCCTATTTATAATCAGGGTGAAACACCTGTGCCAATGCCAAGACAGGGGTGCCAAGA",
    "alignedQuality": []
  }, {
    "id": "",
    "readGroupId": "1",
    "fragmentName": "simread:1:240997787:true",
    "improperPlacement": true,
    "duplicateFragment": false,
    "numberReads": 1,
    "fragmentLength": 0,
    "readNumber": 0,
    "failedVendorQualityChecks": false,
    "alignment": {
      "position": {
        "referenceName": "1",
        "position": "240997787",
        "strand": "POS_STRAND"
      },
      "mappingQuality": 60,
      "cigar": [{
        "operation": "ALIGNMENT_MATCH",
        "operationLength": "75",
        "referenceSequence": ""
      }]
    },
    "secondaryAlignment": false,
    "supplementaryAlignment": false,
    "alignedSequence": "CTTTATTTTTATTTTTAAGGTTTTTTTTGTTTGTTTGTTTTGAGATGGAGTCTCGCTCCACCGCCCAGACTGGAG",
    "alignedQuality": []
  }, {
    "id": "",
    "readGroupId": "1",
    "fragmentName": "simread:1:189606653:true",
    "improperPlacement": true,
    "duplicateFragment": false,
    "numberReads": 1,
    "fragmentLength": 0,
    "readNumber": 0,
    "failedVendorQualityChecks": false,
    "alignment": {
      "position": {
        "referenceName": "1",
        "position": "189606653",
        "strand": "POS_STRAND"
      },
      "mappingQuality": 60,
      "cigar": [{
        "operation": "ALIGNMENT_MATCH",
        "operationLength": "75",
        "referenceSequence": ""
      }]
    },
    "secondaryAlignment": false,
    "supplementaryAlignment": false,
    "alignedSequence": "TGTATCTTCCTCCCCTGCTGTATGTTTCCTGCCCTCAAACATCACACTCCACGTTCTTCAGCTTTAGGACTTGGA",
    "alignedQuality": []
  }, {
    "id": "",
    "readGroupId": "1",
    "fragmentName": "simread:1:207027738:true",
    "improperPlacement": true,
    "duplicateFragment": false,
    "numberReads": 1,
    "fragmentLength": 0,
    "readNumber": 0,
    "failedVendorQualityChecks": false,
    "alignment": {
      "position": {
        "referenceName": "1",
        "position": "207027738",
        "strand": "POS_STRAND"
      },
      "mappingQuality": 60,
      "cigar": [{
        "operation": "ALIGNMENT_MATCH",
        "operationLength": "75",
        "referenceSequence": ""
      }]
    },
    "secondaryAlignment": false,
    "supplementaryAlignment": false,
    "alignedSequence": "TTTAATAAATGTTGATTGTCCTATTTAATTATTCTCAACTTTCCGATTTTATTTCCCATGTAACAGTGTTGTTTT",
    "alignedQuality": []
  }, {
    "id": "",
    "readGroupId": "1",
    "fragmentName": "simread:1:14397233:false",
    "improperPlacement": true,
    "duplicateFragment": false,
    "numberReads": 1,
    "fragmentLength": 0,
    "readNumber": 0,
    "failedVendorQualityChecks": false,
    "alignment": {
      "position": {
        "referenceName": "1",
        "position": "14397233",
        "strand": "NEG_STRAND"
      },
      "mappingQuality": 60,
      "cigar": [{
        "operation": "ALIGNMENT_MATCH",
        "operationLength": "75",
        "referenceSequence": ""
      }]
    },
    "secondaryAlignment": false,
    "supplementaryAlignment": false,
    "alignedSequence": "TAAAATGCCCCCATCTTCCCAGAGCTGCCAGCCCTCACAATGCCAACAGCTAAATGTACCCAAGTGTTACTGAAC",
    "alignedQuality": []
  }, {
    "id": "",
    "readGroupId": "1",
    "fragmentName": "simread:1:240344442:true",
    "improperPlacement": true,
    "duplicateFragment": false,
    "numberReads": 1,
    "fragmentLength": 0,
    "readNumber": 0,
    "failedVendorQualityChecks": false,
    "alignment": {
      "position": {
        "referenceName": "1",
        "position": "240344442",
        "strand": "POS_STRAND"
      },
      "mappingQuality": 24,
      "cigar": [{
        "operation": "ALIGNMENT_MATCH",
        "operationLength": "75",
        "referenceSequence": ""
      }]
    },
    "secondaryAlignment": false,
    "supplementaryAlignment": false,
    "alignedSequence": "TACAGGCACCCACCATCATGCCCAGCTAATTTTTGTATTTTTGTAGAAACGGGGTTTCACCATGTTGGCCCAGCT",
    "alignedQuality": []
  }, {
    "id": "",
    "readGroupId": "1",
    "fragmentName": "simread:1:153978724:false",
    "improperPlacement": true,
    "duplicateFragment": false,
    "numberReads": 1,
    "fragmentLength": 0,
    "readNumber": 0,
    "failedVendorQualityChecks": false,
    "alignment": {
      "position": {
        "referenceName": "1",
        "position": "153978724",
        "strand": "NEG_STRAND"
      },
      "mappingQuality": 60,
      "cigar": [{
        "operation": "ALIGNMENT_MATCH",
        "operationLength": "75",
        "referenceSequence": ""
      }]
    },
    "secondaryAlignment": false,
    "supplementaryAlignment": false,
    "alignedSequence": "GCTCACTGCAGCCTCAACCTCCTGGGCCCAAGTGATTTCATCTTATTTTTGGAAAAAAAAACAAACTAAACCAAA",
    "alignedQuality": []
  }, {
    "id": "",
    "readGroupId": "1",
    "fragmentName": "simread:1:237728409:true",
    "improperPlacement": true,
    "duplicateFragment": false,
    "numberReads": 1,
    "fragmentLength": 0,
    "readNumber": 0,
    "failedVendorQualityChecks": false,
    "alignment": {
      "position": {
        "referenceName": "1",
        "position": "237728409",
        "strand": "POS_STRAND"
      },
      "mappingQuality": 28,
      "cigar": [{
        "operation": "ALIGNMENT_MATCH",
        "operationLength": "75",
        "referenceSequence": ""
      }]
    },
    "secondaryAlignment": false,
    "supplementaryAlignment": false,
    "alignedSequence": "TTTCTTTTTCTTTCTTTCTTTCTTTCTTTCTTTTTCTTTCTTTCTTTCTCTTTCTTTCTTTCTTTCTTTCTTTCT",
    "alignedQuality": []
  }, {
    "id": "",
    "readGroupId": "1",
    "fragmentName": "simread:1:231911906:false",
    "improperPlacement": true,
    "duplicateFragment": false,
    "numberReads": 1,
    "fragmentLength": 0,
    "readNumber": 0,
    "failedVendorQualityChecks": false,
    "alignment": {
      "position": {
        "referenceName": "1",
        "position": "231911906",
        "strand": "NEG_STRAND"
      },
      "mappingQuality": 60,
      "cigar": [{
        "operation": "ALIGNMENT_MATCH",
        "operationLength": "75",
        "referenceSequence": ""
      }]
    },
    "secondaryAlignment": false,
    "supplementaryAlignment": false,
    "alignedSequence": "TCATGTAGCATGCATATGGCTAACGGCAAAGTGAGGGAGGAATAATTATAGTAATAATCACAGTGATGACGTGGA",
    "alignedQuality": []
  }, {
    "id": "",
    "readGroupId": "1",
    "fragmentName": "simread:1:50683371:false",
    "improperPlacement": true,
    "duplicateFragment": false,
    "numberReads": 1,
    "fragmentLength": 0,
    "readNumber": 0,
    "failedVendorQualityChecks": false,
    "alignment": {
      "position": {
        "referenceName": "1",
        "position": "50683371",
        "strand": "NEG_STRAND"
      },
      "mappingQuality": 60,
      "cigar": [{
        "operation": "ALIGNMENT_MATCH",
        "operationLength": "75",
        "referenceSequence": ""
      }]
    },
    "secondaryAlignment": false,
    "supplementaryAlignment": false,
    "alignedSequence": "GCTCAGGCCTTGCAAGAATCTCTACTGCCCAACAAGTCCCTACAAGATGGCATTTAAAAGCAGTCCCTCACGCAC",
    "alignedQuality": []
  }, {
    "id": "",
    "readGroupId": "1",
    "fragmentName": "simread:1:37577445:false",
    "improperPlacement": true,
    "duplicateFragment": false,
    "numberReads": 1,
    "fragmentLength": 0,
    "readNumber": 0,
    "failedVendorQualityChecks": false,
    "alignment": {
      "position": {
        "referenceName": "1",
        "position": "37577445",
        "strand": "NEG_STRAND"
      },
      "mappingQuality": 60,
      "cigar": [{
        "operation": "ALIGNMENT_MATCH",
        "operationLength": "75",
        "referenceSequence": ""
      }]
    },
    "secondaryAlignment": false,
    "supplementaryAlignment": false,
    "alignedSequence": "CCTAGAGAAGCTCCCACTAGGGCTGCAGTCAATTCCCAGGTCTTAGGTGCTGAGCAGTGGGAGGTGGTGGCCATG",
    "alignedQuality": []
  }, {
    "id": "",
    "readGroupId": "1",
    "fragmentName": "simread:1:195211965:false",
    "improperPlacement": true,
    "duplicateFragment": false,
    "numberReads": 1,
    "fragmentLength": 0,
    "readNumber": 0,
    "failedVendorQualityChecks": false,
    "alignment": {
      "position": {
        "referenceName": "1",
        "position": "195211965",
        "strand": "NEG_STRAND"
      },
      "mappingQuality": 60,
      "cigar": [{
        "operation": "ALIGNMENT_MATCH",
        "operationLength": "75",
        "referenceSequence": ""
      }]
    },
    "secondaryAlignment": false,
    "supplementaryAlignment": false,
    "alignedSequence": "AAATAAAGTTTGGCTTTCAGTTGTAACTTTGAATATCTTTATCACAGTTATTTAAAGCCTTTAAAAAGCTTTAAT",
    "alignedQuality": []
  }, {
    "id": "",
    "readGroupId": "1",
    "fragmentName": "simread:1:163841413:false",
    "improperPlacement": true,
    "duplicateFragment": false,
    "numberReads": 1,
    "fragmentLength": 0,
    "readNumber": 0,
    "failedVendorQualityChecks": false,
    "alignment": {
      "position": {
        "referenceName": "1",
        "position": "163841413",
        "strand": "NEG_STRAND"
      },
      "mappingQuality": 60,
      "cigar": [{
        "operation": "ALIGNMENT_MATCH",
        "operationLength": "75",
        "referenceSequence": ""
      }]
    },
    "secondaryAlignment": false,
    "supplementaryAlignment": false,
    "alignedSequence": "TGTGTAACTAACATAATTGGCACTGTCCCTGTAAATTCAAATTGGATATCCTCCCAAATTTTATTTAAGCAATTG",
    "alignedQuality": []
  }, {
    "id": "",
    "readGroupId": "1",
    "fragmentName": "simread:1:101556378:false",
    "improperPlacement": true,
    "duplicateFragment": false,
    "numberReads": 1,
    "fragmentLength": 0,
    "readNumber": 0,
    "failedVendorQualityChecks": false,
    "alignment": {
      "position": {
        "referenceName": "1",
        "position": "101556378",
        "strand": "NEG_STRAND"
      },
      "mappingQuality": 60,
      "cigar": [{
        "operation": "ALIGNMENT_MATCH",
        "operationLength": "75",
        "referenceSequence": ""
      }]
    },
    "secondaryAlignment": false,
    "supplementaryAlignment": false,
    "alignedSequence": "TTTATTTTTTGAGCATGAAAGTAATATATGCTCAGTGTAAACAATTAGGTCATTATAAATATATTTAACAGGAAT",
    "alignedQuality": []
  }, {
    "id": "",
    "readGroupId": "1",
    "fragmentName": "simread:1:20101800:true",
    "improperPlacement": true,
    "duplicateFragment": false,
    "numberReads": 1,
    "fragmentLength": 0,
    "readNumber": 0,
    "failedVendorQualityChecks": false,
    "alignment": {
      "position": {
        "referenceName": "1",
        "position": "20101800",
        "strand": "POS_STRAND"
      },
      "mappingQuality": 35,
      "cigar": [{
        "operation": "ALIGNMENT_MATCH",
        "operationLength": "75",
        "referenceSequence": ""
      }]
    },
    "secondaryAlignment": false,
    "supplementaryAlignment": false,
    "alignedSequence": "CTCAGGTGATCCACCCGCCTCGGCCTCCCAAAGTGCTGGGACTACAGGCATGAGGCACCGCGCCTGGCCAGGACT",
    "alignedQuality": []
  }, {
    "id": "",
    "readGroupId": "1",
    "fragmentName": "simread:1:186794283:true",
    "improperPlacement": true,
    "duplicateFragment": false,
    "numberReads": 1,
    "fragmentLength": 0,
    "readNumber": 0,
    "failedVendorQualityChecks": false,
    "alignment": {
      "position": {
        "referenceName": "1",
        "position": "186794283",
        "strand": "POS_STRAND"
      },
      "mappingQuality": 60,
      "cigar": [{
        "operation": "ALIGNMENT_MATCH",
        "operationLength": "75",
        "referenceSequence": ""
      }]
    },
    "secondaryAlignment": false,
    "supplementaryAlignment": false,
    "alignedSequence": "GACAAGATAGTACTTGAGCTAAGCCTTGCAGGTTGAGTAGGATTATTCTAGTGGAATTTAGGGAAACGATGTGCA",
    "alignedQuality": []
  }, {
    "id": "",
    "readGroupId": "1",
    "fragmentName": "simread:1:165341382:true",
    "improperPlacement": true,
    "duplicateFragment": false,
    "numberReads": 1,
    "fragmentLength": 0,
    "readNumber": 0,
    "failedVendorQualityChecks": false,
    "alignment": {
      "position": {
        "referenceName": "1",
        "position": "165341382",
        "strand": "POS_STRAND"
      },
      "mappingQuality": 60,
      "cigar": [{
        "operation": "ALIGNMENT_MATCH",
        "operationLength": "75",
        "referenceSequence": ""
      }]
    },
    "secondaryAlignment": false,
    "supplementaryAlignment": false,
    "alignedSequence": "CTACTCTCATTGACTGTTCAATGCCTATACAAGTAAAACTTTACCAGCACCCAAGTCAAAAAGAAAAAAAAGGGG",
    "alignedQuality": []
  }, {
    "id": "",
    "readGroupId": "1",
    "fragmentName": "simread:1:5469106:true",
    "improperPlacement": true,
    "duplicateFragment": false,
    "numberReads": 1,
    "fragmentLength": 0,
    "readNumber": 0,
    "failedVendorQualityChecks": false,
    "alignment": {
      "position": {
        "referenceName": "1",
        "position": "5469106",
        "strand": "POS_STRAND"
      },
      "mappingQuality": 60,
      "cigar": [{
        "operation": "ALIGNMENT_MATCH",
        "operationLength": "75",
        "referenceSequence": ""
      }]
    },
    "secondaryAlignment": false,
    "supplementaryAlignment": false,
    "alignedSequence": "CTCATTCTCTCTCCTGCTGCACTGTGAAGAGGTGCCTGTTGCCAAGAGTATAAGTTTCCTGAGGCCTCCCAGGCC",
    "alignedQuality": []
  }, {
    "id": "",
    "readGroupId": "1",
    "fragmentName": "simread:1:89554252:false",
    "improperPlacement": true,
    "duplicateFragment": false,
    "numberReads": 1,
    "fragmentLength": 0,
    "readNumber": 0,
    "failedVendorQualityChecks": false,
    "alignment": {
      "position": {
        "referenceName": "1",
        "position": "89554252",
        "strand": "NEG_STRAND"
      },
      "mappingQuality": 60,
      "cigar": [{
        "operation": "ALIGNMENT_MATCH",
        "operationLength": "75",
        "referenceSequence": ""
      }]
    },
    "secondaryAlignment": false,
    "supplementaryAlignment": false,
    "alignedSequence": "AAATTAAACAGCTCGTTTAACTGATAATCCATACTATATTTGAGTAGGGCTGTCACATGGTTGGAACCTCCGGTT",
    "alignedQuality": []
  }, {
    "id": "",
    "readGroupId": "1",
    "fragmentName": "simread:1:169801933:true",
    "improperPlacement": true,
    "duplicateFragment": false,
    "numberReads": 1,
    "fragmentLength": 0,
    "readNumber": 0,
    "failedVendorQualityChecks": false,
    "alignment": {
      "position": {
        "referenceName": "1",
        "position": "169801933",
        "strand": "POS_STRAND"
      },
      "mappingQuality": 40,
      "cigar": [{
        "operation": "ALIGNMENT_MATCH",
        "operationLength": "75",
        "referenceSequence": ""
      }]
    },
    "secondaryAlignment": false,
    "supplementaryAlignment": false,
    "alignedSequence": "AGACTGGGTCTCACTATGTTGCCTAGGCTGGTCTCAAACTCCTGGGCTCAAGTGATCCATCTCTGCCTTCCAAAG",
    "alignedQuality": []
  }],
  "nextPageToken": ""
}
```

**Pull request closed without merging**
